blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/az4WxZSeDU
    about: If you are having issues, come to our Discord server and we will try to help you out!
