name: RU Bug Report
description: Сообщайте об ошибках или проблемах, связанных с модпаком.
labels: bug
assignees: Disguys
body:
  - type: markdown
    attributes:
      value: |
        Прежде чем сообщать о проблеме, пожалуйста, убедитесь, что Вы используете последнюю версию МодПака Valmata.
        
  - type: textarea
    attributes:
      label: Ожидаемое поведение
      description: То, чего вы ожидали.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Cite any steps you did to reproduce the bug. You can also cite videos, schematics, maps...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I use the latest version of Valmata ModPack.
          required: true
        - label: My version of Minecraft is supported Valmata ModPack.
          required: true
  - type: textarea
    attributes:
      label: Crash log
      description: |
        Please send your crash log below.
        Please use a pasting service like Pastebin, Hastebin or Github Gist..
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information i receive, the quicker and more effective i can be at finding the solution to the issue.
    validations:
      required: false
