name: Bug report
description: "[RU] Сообщайте об ошибках или проблемах, связанных с модпаком."
labels: bug
assignees: Disguys
body:
  - type: markdown
    attributes:
      value: |
        "Прежде чем сообщать о проблеме, пожалуйста, убедитесь, что Вы используете последнюю версию МодПака Valmata."
        
  - type: textarea
    attributes:
      label: "Ожидаемое поведение"
      description: "То, чего вы ожидали."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Актуальное поведение"
      description: "Что на самом деле произошло."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Шаги по воспроизведению"
      description: "Укажите все шаги, которые вы сделали, чтобы воспроизвести ошибку. Вы также можете отправить видео, схемы, карты..."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Соглашения"
      description: "Пожалуйста, согласитесь со следующим."
      options:
        - label: "Я использую последнюю версию МодПака Valmata."
          required: true
  - type: textarea
    attributes:
      label: "Краш лог"
      description: |
        "Пожалуйста, отправьте свой краш лог ниже."
        "Пожалуйста, используйте службу вставки, такие как: Pastebin, Hastebin или Github Gist."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Другое"
      description: |
        "Пожалуйста, включите другую полезную информацию ниже."
        "Чем больше информации я получаю, тем быстрее и эффективнее я смогу найти решение проблемы."
    validations:
      required: false
