name: RU Bug Report
description: Сообщайте об ошибках или проблемах, связанных с модпаком.
labels: bug
assignees: Disguys
body:
  - type: markdown
    attributes:
      value: |
        Прежде чем сообщать о проблеме, пожалуйста, убедитесь, что Вы используете последнюю версию МодПака Valmata.
        
  - type: textarea
    attributes:
      label: Ожидаемое поведение
      description: То, чего вы ожидали.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Актуальное поведение
      description: Что на самом деле произошло.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Шаги по воспроизведению
      description: Укажите все шаги, которые вы сделали, чтобы воспроизвести ошибку. Вы также можете отправить видео, схемы, карты...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Соглашения
      description: Пожалуйста, согласитесь со следующим.
      options:
        - label: Я использую последнюю версию МодПака Valmata.
          required: true
  - type: textarea
    attributes:
      label: Crash log
      description: |
        Please send your crash log below.
        Please use a pasting service like Pastebin, Hastebin or Github Gist..
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information i receive, the quicker and more effective i can be at finding the solution to the issue.
    validations:
      required: false
